### ISSUE TITLE
Lien non fonctionnel

### ISSUE THREAD

**Issue by Ritooon** [anct-cnum/portail-conseiller#181]
Hello, 

Ce lien ne fonctionne pas : https://aide.conseiller-numerique.gouv.fr/fr/article/quelle-structure-peut-candidater-pour-recevoir-des-conseillers-numeriques-a74m0w/

Il est trouvable sur cette page : https://conseiller-numerique.gouv.fr/aide-structure (Texte : *Accédez à la liste des structures éligibles ici.")

**Comment by Ritooon** [comment]
Mauvais repo, désolé

**Comment by jystervinou** [comment]
Bonjour @Ritooon merci pour l'info, ça a été corrigé.
